# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://soarce.local:8001/



###

POST http://soarce.local:8001/receive
Content-Type: application/json

{
  "header": {
    "type": "trace",
    "host": "billingApplication",
    "request_time": 1749425577.224946,
    "request_id": "a20023e844d6a040",
    "get": {
      "action": "details",
      "invoice": "825896460"
    },
    "post": [],
    "server": {
      "HTTP_HOST": "localhost:8110",
      "HTTP_CONNECTION": "keep-alive",
      "HTTP_SEC_CH_UA": "\"Brave\";v=\"137\", \"Chromium\";v=\"137\", \"Not\/A)Brand\";v=\"24\"",
      "HTTP_SEC_CH_UA_MOBILE": "?0",
      "HTTP_SEC_CH_UA_PLATFORM": "\"Linux\"",
      "HTTP_UPGRADE_INSECURE_REQUESTS": "1",
      "HTTP_USER_AGENT": "Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/137.0.0.0 Safari\/537.36",
      "HTTP_ACCEPT": "text\/html,application\/xhtml+xml,application\/xml;q=0.9,image\/avif,image\/webp,image\/apng,*\/*;q=0.8",
      "HTTP_SEC_GPC": "1",
      "HTTP_ACCEPT_LANGUAGE": "en-US,en;q=0.5",
      "HTTP_SEC_FETCH_SITE": "same-origin",
      "HTTP_SEC_FETCH_MODE": "navigate",
      "HTTP_SEC_FETCH_USER": "?1",
      "HTTP_SEC_FETCH_DEST": "document",
      "HTTP_REFERER": "http:\/\/localhost:8110\/index.php?action=invoices&client=27",
      "HTTP_ACCEPT_ENCODING": "gzip, deflate, br, zstd",
      "PATH": "\/usr\/local\/sbin:\/usr\/local\/bin:\/usr\/sbin:\/usr\/bin:\/sbin:\/bin",
      "SERVER_SIGNATURE": "<address>Apache\/2.4.52 (Debian) Server at localhost Port 8110<\/address>\n",
      "SERVER_SOFTWARE": "Apache\/2.4.52 (Debian)",
      "SERVER_NAME": "localhost",
      "SERVER_ADDR": "172.18.0.9",
      "SERVER_PORT": "8110",
      "REMOTE_ADDR": "172.18.0.1",
      "DOCUMENT_ROOT": "\/var\/www\/html",
      "REQUEST_SCHEME": "http",
      "CONTEXT_PREFIX": "",
      "CONTEXT_DOCUMENT_ROOT": "\/var\/www\/html",
      "SERVER_ADMIN": "webmaster@localhost",
      "SCRIPT_FILENAME": "\/var\/www\/html\/index.php",
      "REMOTE_PORT": "41666",
      "GATEWAY_INTERFACE": "CGI\/1.1",
      "SERVER_PROTOCOL": "HTTP\/1.1",
      "REQUEST_METHOD": "GET",
      "QUERY_STRING": "action=details&invoice=825896460",
      "REQUEST_URI": "\/index.php?action=details&invoice=825896460",
      "SCRIPT_NAME": "\/index.php",
      "PHP_SELF": "\/index.php",
      "REQUEST_TIME_FLOAT": 1749425577.214528,
      "REQUEST_TIME": 1749425577,
      "argv": [
        "action=details&invoice=825896460"
      ],
      "argc": 1
    },
    "env": {
      "HOSTNAME": "89f6826b137a",
      "PHP_VERSION": "7.3.33",
      "APACHE_CONFDIR": "\/etc\/apache2",
      "PHP_INI_DIR": "\/usr\/local\/etc\/php",
      "GPG_KEYS": "CBAF69F173A0FEA4B537F470D66C9593118BCCB6 F38252826ACD957EF380D39F2F7956BC5DA04B5D",
      "PHP_LDFLAGS": "-Wl,-O1 -pie",
      "PWD": "\/var\/www\/html",
      "APACHE_LOG_DIR": "\/var\/log\/apache2",
      "LANG": "C",
      "PHP_SHA256": "166eaccde933381da9516a2b70ad0f447d7cec4b603d07b9a916032b215b90cc",
      "APACHE_PID_FILE": "\/var\/run\/apache2\/apache2.pid",
      "PHPIZE_DEPS": "autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkg-config \t\tre2c",
      "SOARCE_PRESHARED_SECRET": "K25NZK0whQeu~**qbp0",
      "PHP_URL": "https:\/\/www.php.net\/distributions\/php-7.3.33.tar.xz",
      "APACHE_RUN_GROUP": "www-data",
      "APACHE_LOCK_DIR": "\/var\/lock\/apache2",
      "SHLVL": "0",
      "SOARCE_APPLICATION_NAME": "billingApplication",
      "PHP_CFLAGS": "-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
      "APACHE_RUN_DIR": "\/var\/run\/apache2",
      "APACHE_ENVVARS": "\/etc\/apache2\/envvars",
      "APACHE_RUN_USER": "www-data",
      "PATH": "\/usr\/local\/sbin:\/usr\/local\/bin:\/usr\/sbin:\/usr\/bin:\/sbin:\/bin",
      "PHP_ASC_URL": "https:\/\/www.php.net\/distributions\/php-7.3.33.tar.xz.asc",
      "PHP_CPPFLAGS": "-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
    }
  },
  "payload": {
    "functions": {
      "\/var\/www\/html\/vendor\/soarce\/client\/src\/execute.php": {
        "register_shutdown_function": {
          "type": "0",
          "count": 1,
          "walltime": 6.000000000000796e-6,
          "number": 0
        }
      },
      "\/var\/www\/html\/vendor\/composer\/autoload_real.php": {
        "Soarce\\Pipe->__destruct": {
          "type": "1",
          "count": 1,
          "walltime": 1.9999999999985307e-6,
          "number": 1
        }
      },
      "\/var\/www\/html\/details.php": {
        "file_get_contents": {
          "type": "0",
          "count": 1,
          "walltime": 0.20854099999999998,
          "number": 3
        },
        "json_decode": {
          "type": "0",
          "count": 1,
          "walltime": 2.4999999999997247e-5,
          "number": 4
        },
        "print_r": {
          "type": "0",
          "count": 1,
          "walltime": 1.4000000000014001e-5,
          "number": 5
        }
      },
      "\/var\/www\/html\/index.php": {
        "include": {
          "type": "1",
          "count": 1,
          "walltime": 0.208634,
          "number": 2
        }
      }
    },
    "calls": {
      "2": {
        "3": 1,
        "4": 1,
        "5": 1
      },
      "6": {
        "7": 1
      }
    }
  }
}

###


POST http://soarce.local:8001/receive
Content-Type: application/json

{
  "header": {
    "type": "coverage",
    "host": "billingApplication",
    "request_time": 1749425577.224946,
    "request_id": "a20023e844d6a040",
    "get": {
      "action": "details",
      "invoice": "825896460"
    },
    "post": [],
    "server": {
      "HTTP_HOST": "localhost:8110",
      "HTTP_CONNECTION": "keep-alive",
      "HTTP_SEC_CH_UA": "\"Brave\";v=\"137\", \"Chromium\";v=\"137\", \"Not\/A)Brand\";v=\"24\"",
      "HTTP_SEC_CH_UA_MOBILE": "?0",
      "HTTP_SEC_CH_UA_PLATFORM": "\"Linux\"",
      "HTTP_UPGRADE_INSECURE_REQUESTS": "1",
      "HTTP_USER_AGENT": "Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/137.0.0.0 Safari\/537.36",
      "HTTP_ACCEPT": "text\/html,application\/xhtml+xml,application\/xml;q=0.9,image\/avif,image\/webp,image\/apng,*\/*;q=0.8",
      "HTTP_SEC_GPC": "1",
      "HTTP_ACCEPT_LANGUAGE": "en-US,en;q=0.5",
      "HTTP_SEC_FETCH_SITE": "same-origin",
      "HTTP_SEC_FETCH_MODE": "navigate",
      "HTTP_SEC_FETCH_USER": "?1",
      "HTTP_SEC_FETCH_DEST": "document",
      "HTTP_REFERER": "http:\/\/localhost:8110\/index.php?action=invoices&client=27",
      "HTTP_ACCEPT_ENCODING": "gzip, deflate, br, zstd",
      "PATH": "\/usr\/local\/sbin:\/usr\/local\/bin:\/usr\/sbin:\/usr\/bin:\/sbin:\/bin",
      "SERVER_SIGNATURE": "<address>Apache\/2.4.52 (Debian) Server at localhost Port 8110<\/address>\n",
      "SERVER_SOFTWARE": "Apache\/2.4.52 (Debian)",
      "SERVER_NAME": "localhost",
      "SERVER_ADDR": "172.18.0.9",
      "SERVER_PORT": "8110",
      "REMOTE_ADDR": "172.18.0.1",
      "DOCUMENT_ROOT": "\/var\/www\/html",
      "REQUEST_SCHEME": "http",
      "CONTEXT_PREFIX": "",
      "CONTEXT_DOCUMENT_ROOT": "\/var\/www\/html",
      "SERVER_ADMIN": "webmaster@localhost",
      "SCRIPT_FILENAME": "\/var\/www\/html\/index.php",
      "REMOTE_PORT": "41666",
      "GATEWAY_INTERFACE": "CGI\/1.1",
      "SERVER_PROTOCOL": "HTTP\/1.1",
      "REQUEST_METHOD": "GET",
      "QUERY_STRING": "action=details&invoice=825896460",
      "REQUEST_URI": "\/index.php?action=details&invoice=825896460",
      "SCRIPT_NAME": "\/index.php",
      "PHP_SELF": "\/index.php",
      "REQUEST_TIME_FLOAT": 1749425577.214528,
      "REQUEST_TIME": 1749425577,
      "argv": [
        "action=details&invoice=825896460"
      ],
      "argc": 1
    },
    "env": {
      "HOSTNAME": "89f6826b137a",
      "PHP_VERSION": "7.3.33",
      "APACHE_CONFDIR": "\/etc\/apache2",
      "PHP_INI_DIR": "\/usr\/local\/etc\/php",
      "GPG_KEYS": "CBAF69F173A0FEA4B537F470D66C9593118BCCB6 F38252826ACD957EF380D39F2F7956BC5DA04B5D",
      "PHP_LDFLAGS": "-Wl,-O1 -pie",
      "PWD": "\/var\/www\/html",
      "APACHE_LOG_DIR": "\/var\/log\/apache2",
      "LANG": "C",
      "PHP_SHA256": "166eaccde933381da9516a2b70ad0f447d7cec4b603d07b9a916032b215b90cc",
      "APACHE_PID_FILE": "\/var\/run\/apache2\/apache2.pid",
      "PHPIZE_DEPS": "autoconf \t\tdpkg-dev \t\tfile \t\tg++ \t\tgcc \t\tlibc-dev \t\tmake \t\tpkg-config \t\tre2c",
      "SOARCE_PRESHARED_SECRET": "K25NZK0whQeu~**qbp0",
      "PHP_URL": "https:\/\/www.php.net\/distributions\/php-7.3.33.tar.xz",
      "APACHE_RUN_GROUP": "www-data",
      "APACHE_LOCK_DIR": "\/var\/lock\/apache2",
      "SHLVL": "0",
      "SOARCE_APPLICATION_NAME": "billingApplication",
      "PHP_CFLAGS": "-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64",
      "APACHE_RUN_DIR": "\/var\/run\/apache2",
      "APACHE_ENVVARS": "\/etc\/apache2\/envvars",
      "APACHE_RUN_USER": "www-data",
      "PATH": "\/usr\/local\/sbin:\/usr\/local\/bin:\/usr\/sbin:\/usr\/bin:\/sbin:\/bin",
      "PHP_ASC_URL": "https:\/\/www.php.net\/distributions\/php-7.3.33.tar.xz.asc",
      "PHP_CPPFLAGS": "-fstack-protector-strong -fpic -fpie -O2 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64"
    }
  },
  "payload": {
    "\/var\/www\/html\/vendor\/soarce\/client\/src\/Pipe\/Handler.php": {
      "26": -1,
      "27": -1,
      "28": -1,
      "36": -1,
      "37": -1,
      "38": -1,
      "39": -1,
      "42": -1,
      "43": -2,
      "50": -1,
      "51": -1,
      "52": -1,
      "53": -1,
      "55": -1,
      "56": -2
    },
    "\/var\/www\/html\/vendor\/soarce\/client\/src\/RedisMutex.php": {
      "27": -1,
      "28": -1,
      "29": -1,
      "30": -1,
      "36": -1,
      "37": -1,
      "38": -1,
      "40": -1,
      "46": -1,
      "47": -1,
      "48": -1,
      "55": -1,
      "56": -1,
      "57": -1,
      "58": -2,
      "66": -1,
      "67": -1,
      "74": -1,
      "75": -2,
      "82": -1,
      "83": -2,
      "91": -1,
      "92": -1,
      "95": -1,
      "96": -1,
      "97": -1,
      "99": -1,
      "100": -2
    },
    "\/var\/www\/html\/vendor\/soarce\/client\/src\/RequestTracking.php": {
      "31": -1,
      "32": -1,
      "39": -1,
      "40": -1,
      "44": -1,
      "47": -1,
      "48": -1,
      "52": -1,
      "53": -1,
      "57": -1,
      "58": -1,
      "59": -1,
      "61": -1,
      "62": -2,
      "69": 1,
      "70": 1,
      "71": 1,
      "81": -1,
      "84": -1,
      "85": -1,
      "89": -1,
      "92": -1,
      "95": -1,
      "98": -1,
      "99": -2,
      "106": -1,
      "107": -2,
      "114": -1,
      "115": -1,
      "118": -1,
      "119": -2,
      "126": 1,
      "127": -1,
      "129": 1,
      "130": -2
    },
    "\/var\/www\/html\/vendor\/soarce\/client\/src\/execute.php": {
      "54": 1,
      "55": 1,
      "56": 1,
      "60": 1,
      "61": 1,
      "64": 1,
      "67": 1,
      "70": 1,
      "71": 1,
      "74": -1,
      "75": -1,
      "76": -1,
      "77": -1,
      "82": -1,
      "83": -1,
      "84": -1,
      "88": -1,
      "90": -1,
      "92": -1,
      "93": 1,
      "95": 1
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Command\/Command.php": {
      "33": 1,
      "34": -2,
      "41": 1,
      "42": 1,
      "43": 1,
      "50": -1,
      "51": -1,
      "52": -1,
      "59": 1,
      "60": -2,
      "67": -1,
      "68": -1,
      "70": -1,
      "77": -1,
      "78": -1,
      "85": -1,
      "86": -1,
      "88": -1,
      "95": 1,
      "96": -2,
      "107": -1,
      "108": -1,
      "111": -1,
      "112": -2,
      "123": -1,
      "124": -1,
      "127": -1,
      "128": -2
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Connection\/AbstractConnection.php": {
      "37": -1,
      "38": -1,
      "46": -1,
      "47": -1,
      "72": -1,
      "73": -2,
      "80": -1,
      "81": -1,
      "83": -1,
      "86": -1,
      "87": -2,
      "94": -1,
      "95": -1,
      "102": -1,
      "103": -1,
      "110": 1,
      "112": 1,
      "113": -2,
      "120": 1,
      "121": -2,
      "133": -1,
      "135": -1,
      "136": -1,
      "139": -1,
      "140": -1,
      "143": -1,
      "144": -2,
      "154": -1,
      "155": -1,
      "157": -1,
      "166": -1,
      "167": -1,
      "169": -1,
      "176": 1,
      "177": 1,
      "180": -1,
      "182": -1,
      "183": -2,
      "190": -1,
      "191": -2,
      "200": -1,
      "201": -1,
      "204": -1,
      "205": -2,
      "212": -1,
      "213": -1,
      "216": -1,
      "217": -2,
      "224": -1,
      "225": -2
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Configuration\/Options.php": {
      "33": -1,
      "34": -1,
      "35": -1,
      "36": -1,
      "46": -1,
      "53": -2,
      "60": -1,
      "61": -1,
      "62": -1,
      "64": -1,
      "66": -1,
      "74": -1,
      "75": -1,
      "77": -2,
      "85": -1,
      "86": -1,
      "87": -1,
      "88": -2,
      "95": -1,
      "96": -1,
      "99": -1,
      "100": -1,
      "101": -1,
      "103": -1,
      "104": -1,
      "107": -1,
      "108": -1,
      "109": -1,
      "110": -1,
      "113": -1,
      "116": -1,
      "117": -1,
      "120": -1,
      "121": -2
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Command\/KeyExpire.php": {
      "26": -1,
      "27": -2
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Command\/ListRemove.php": {
      "19": 1,
      "26": 1,
      "27": -2,
      "29": 1
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Connection\/Factory.php": {
      "47": -1,
      "48": -1,
      "51": -1,
      "53": -1,
      "54": -1,
      "55": -1,
      "59": -1,
      "60": -2,
      "67": -1,
      "68": -1,
      "75": -1,
      "76": -1,
      "83": -1,
      "84": -1,
      "87": -1,
      "89": -1,
      "90": -1,
      "93": -1,
      "95": -1,
      "96": -1,
      "98": -1,
      "99": -1,
      "102": -1,
      "103": -1,
      "105": -1,
      "109": -1,
      "110": -2,
      "117": -1,
      "118": -1,
      "120": -1,
      "132": -1,
      "133": -1,
      "142": -1,
      "143": -2,
      "154": -1,
      "155": -1,
      "157": -1,
      "160": -1,
      "161": -1,
      "164": -1,
      "165": -2,
      "174": -1,
      "176": -1,
      "177": -1,
      "178": -1,
      "179": -1,
      "181": -1,
      "182": -1,
      "186": -1,
      "187": -1,
      "188": -1,
      "191": -1
    },
    "\/var\/www\/html\/vendor\/soarce\/client\/src\/FrontController.php": {
      "26": -1,
      "27": -1,
      "36": -1,
      "37": -1,
      "40": -1,
      "41": -1,
      "42": -1,
      "45": -1,
      "46": -1,
      "49": -1,
      "52": -1,
      "54": -1,
      "55": -1,
      "56": -1,
      "60": -1,
      "63": -1,
      "64": -2,
      "71": -1,
      "72": -1,
      "75": -1,
      "76": -1,
      "79": -1,
      "80": -1,
      "83": -1,
      "84": -2,
      "92": -1,
      "93": -1,
      "96": -1,
      "99": -1,
      "100": -1,
      "103": -1,
      "104": -2
    },
    "\/var\/www\/html\/vendor\/symfony\/deprecation-contracts\/function.php": {
      "25": -1,
      "26": -1
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Connection\/Parameters.php": {
      "36": -1,
      "37": -1,
      "46": -1,
      "47": -2,
      "59": -1,
      "60": -1,
      "63": -1,
      "64": -2,
      "86": -1,
      "89": -1,
      "92": -1,
      "93": -1,
      "97": -1,
      "98": -1,
      "99": -1,
      "101": -1,
      "104": -1,
      "105": -1,
      "106": -1,
      "108": -1,
      "111": -1,
      "112": -1,
      "113": -1,
      "114": -1,
      "116": -1,
      "119": -1,
      "120": -1,
      "121": -1,
      "123": -1,
      "126": -1,
      "127": -1,
      "129": -1,
      "130": -1,
      "132": -1,
      "137": -1,
      "138": -2,
      "149": -1,
      "150": -2,
      "157": -1,
      "158": -1,
      "160": -1,
      "167": -1,
      "168": -2,
      "175": -1,
      "176": -2,
      "183": -1,
      "184": -2
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Command\/ListPopLastBlocking.php": {
      "26": -1,
      "27": -2
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Profile\/RedisVersion320.php": {
      "26": -1,
      "27": -2,
      "38": -1,
      "280": -2
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Profile\/RedisProfile.php": {
      "32": -1,
      "33": -1,
      "48": -1,
      "49": -2,
      "56": -1,
      "57": -1,
      "58": -1,
      "62": -1,
      "63": -2,
      "75": -1,
      "76": -1,
      "78": -1,
      "85": 1,
      "87": 1,
      "88": -1,
      "91": 1,
      "92": 1,
      "93": 1,
      "95": 1,
      "96": -1,
      "99": 1,
      "100": -2,
      "112": -1,
      "114": -1,
      "115": -1,
      "118": -1,
      "119": -1,
      "126": -1,
      "127": -1,
      "134": -1,
      "135": -2,
      "144": -1,
      "145": -2
    },
    "\/var\/www\/html\/vendor\/composer\/ClassLoader.php": {
      "108": -1,
      "109": -1,
      "110": -1,
      "117": -1,
      "118": -1,
      "121": -1,
      "122": -2,
      "129": -1,
      "130": -2,
      "137": -1,
      "138": -2,
      "145": -1,
      "146": -2,
      "153": -1,
      "154": -2,
      "163": -1,
      "164": -1,
      "166": -1,
      "168": -1,
      "182": -1,
      "183": -1,
      "184": -1,
      "185": -1,
      "186": -1,
      "187": -1,
      "190": -1,
      "191": -1,
      "196": -1,
      "199": -1,
      "200": -1,
      "201": -1,
      "203": -1,
      "205": -1,
      "206": -1,
      "207": -1,
      "208": -1,
      "211": -1,
      "212": -1,
      "216": -1,
      "232": -1,
      "233": -1,
      "235": -1,
      "236": -1,
      "237": -1,
      "238": -1,
      "241": -1,
      "242": -1,
      "246": -1,
      "248": -1,
      "249": -1,
      "250": -1,
      "252": -1,
      "253": -1,
      "254": -1,
      "256": -1,
      "257": -1,
      "258": -1,
      "262": -1,
      "263": -1,
      "267": -1,
      "280": -1,
      "281": -1,
      "283": -1,
      "285": -1,
      "300": -1,
      "301": -1,
      "303": -1,
      "304": -1,
      "305": -1,
      "307": -1,
      "308": -1,
      "310": -1,
      "321": -1,
      "322": -1,
      "332": -1,
      "333": -2,
      "345": -1,
      "346": -1,
      "355": -1,
      "356": -2,
      "367": -1,
      "368": -1,
      "377": -1,
      "378": -2,
      "389": -1,
      "391": -1,
      "392": -1,
      "395": -1,
      "396": -1,
      "398": -1,
      "399": -1,
      "401": -1,
      "410": -1,
      "412": -1,
      "413": -1,
      "415": -1,
      "425": 1,
      "426": 1,
      "427": 1,
      "429": 1,
      "432": -1,
      "433": -2,
      "445": 1,
      "446": -1,
      "448": 1,
      "449": -1,
      "451": 1,
      "452": -1,
      "453": -1,
      "454": -1,
      "458": 1,
      "461": 1,
      "462": -1,
      "465": 1,
      "466": -1,
      "469": 1,
      "471": -1,
      "474": 1,
      "475": -2,
      "484": -1,
      "485": -2,
      "495": 1,
      "497": 1,
      "498": 1,
      "499": 1,
      "500": 1,
      "501": 1,
      "502": 1,
      "503": 1,
      "504": 1,
      "505": 1,
      "506": 1,
      "507": 1,
      "515": -1,
      "516": -1,
      "517": -1,
      "522": -1,
      "524": -1,
      "525": -1,
      "528": -1,
      "531": -1,
      "532": -1,
      "533": -1,
      "534": -1,
      "535": -1,
      "536": -1,
      "544": -1,
      "545": -1,
      "546": -1,
      "551": -1,
      "552": -1,
      "555": -1,
      "556": -2,
      "563": -1,
      "564": -1,
      "575": -1,
      "576": 1,
      "577": 1,
      "578": -1
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Command\/ListPushTail.php": {
      "26": -1,
      "27": -2,
      "34": -1,
      "35": -2
    },
    "\/var\/www\/html\/vendor\/autoload.php": {
      "22": 1
    },
    "\/var\/www\/html\/details.php": {
      "2": 1,
      "4": 1,
      "5": -1,
      "6": -1,
      "9": 1,
      "11": 1,
      "14": 1,
      "21": 1,
      "24": 1
    },
    "\/var\/www\/html\/vendor\/soarce\/client\/src\/Config.php": {
      "44": -1,
      "45": -1,
      "48": -1,
      "49": -2,
      "56": -1,
      "57": -1,
      "60": -1,
      "61": -2,
      "68": -1,
      "69": -1,
      "72": -1,
      "73": -2,
      "80": -1,
      "81": -1,
      "88": -1,
      "89": -1,
      "91": -1,
      "92": -2,
      "99": -1,
      "100": -1,
      "107": -1,
      "108": -1,
      "109": -1,
      "110": -1,
      "111": -2,
      "118": -1,
      "119": -1,
      "121": -1,
      "122": -2,
      "129": -1,
      "130": -1,
      "137": -1,
      "138": -1,
      "139": -1,
      "140": -1,
      "141": -1,
      "143": -1,
      "147": -1,
      "148": -2,
      "155": -1,
      "156": -1,
      "163": -1,
      "164": -1,
      "165": -1,
      "166": -1,
      "167": -1,
      "169": -1,
      "173": -1,
      "174": -2,
      "181": -1,
      "182": -1
    },
    "\/var\/www\/html\/index.php": {
      "8": 1,
      "10": 1,
      "11": 1,
      "14": 1,
      "17": 1,
      "18": 1,
      "19": 1,
      "24": 1
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Client.php": {
      "55": -1,
      "56": -1,
      "57": -1,
      "58": -1,
      "73": -1,
      "74": -1,
      "77": -1,
      "78": -1,
      "81": -1,
      "82": -2,
      "105": -1,
      "106": -1,
      "109": -1,
      "110": -1,
      "113": -1,
      "114": -1,
      "115": -1,
      "118": -1,
      "120": -1,
      "121": -1,
      "122": -1,
      "123": -1,
      "124": -1,
      "126": -1,
      "127": -1,
      "128": -1,
      "130": -1,
      "131": -1,
      "134": -1,
      "135": -1,
      "138": -1,
      "141": -1,
      "142": -1,
      "143": -1,
      "145": -1,
      "148": -1,
      "149": -2,
      "161": -1,
      "162": -1,
      "164": -1,
      "165": -1,
      "166": -1,
      "170": -1,
      "171": -1,
      "172": -2,
      "179": -1,
      "180": -2,
      "187": -1,
      "188": -2,
      "203": -1,
      "204": -1,
      "207": -1,
      "208": -2,
      "215": -1,
      "216": -1,
      "223": -1,
      "224": -1,
      "234": -1,
      "235": -1,
      "244": -1,
      "245": -2,
      "252": -1,
      "253": -2,
      "267": -1,
      "268": -1,
      "269": -1,
      "273": -1,
      "274": -2,
      "291": -1,
      "293": -1,
      "294": -1,
      "297": -1,
      "298": -1,
      "299": -1,
      "302": -1,
      "305": -1,
      "306": -2,
      "313": 1,
      "314": 1,
      "316": -2,
      "323": 1,
      "324": -2,
      "331": 1,
      "333": 1,
      "334": -1,
      "335": -1,
      "338": -1,
      "341": 1,
      "342": -2,
      "356": -1,
      "357": -1,
      "358": -1,
      "360": -1,
      "362": -1,
      "363": -1,
      "366": -1,
      "369": -1,
      "370": -1,
      "373": -1,
      "374": -2,
      "389": -1,
      "390": -1,
      "391": -1,
      "393": -1,
      "394": -1,
      "395": -1,
      "396": -1,
      "398": -1,
      "399": -1,
      "401": -1,
      "404": -1,
      "406": -2,
      "418": -1,
      "419": -2,
      "431": -1,
      "432": -1,
      "433": -1,
      "434": -1,
      "436": -1,
      "442": -1,
      "444": -1,
      "445": -1,
      "448": -1,
      "449": -2,
      "461": -1,
      "462": -2,
      "474": -1,
      "476": -1,
      "477": -1,
      "480": -1,
      "481": -2,
      "493": -1,
      "494": -2,
      "506": -1,
      "508": -1,
      "509": -1,
      "512": -1,
      "513": -1,
      "514": -1,
      "517": -1,
      "526": -1,
      "527": -2,
      "535": -1,
      "536": -1,
      "538": -1,
      "539": -1,
      "540": -1,
      "544": -1,
      "545": -1,
      "548": -1,
      "549": -2
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Configuration\/ConnectionFactoryOption.php": {
      "30": -1,
      "31": -1,
      "32": -1,
      "33": -1,
      "35": -1,
      "36": -1,
      "39": -1,
      "41": -1,
      "42": -1,
      "45": -2,
      "52": -1,
      "54": -1,
      "55": -1,
      "58": -1,
      "59": -2
    },
    "\/var\/www\/html\/vendor\/soarce\/client\/src\/Pipe.php": {
      "19": -1,
      "20": -1,
      "27": 1,
      "28": -2,
      "35": -1,
      "36": -2,
      "43": -1,
      "44": -1,
      "51": 1,
      "52": -1,
      "54": 1
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Command\/ListPushHead.php": {
      "26": -1,
      "27": -2
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Connection\/StreamConnection.php": {
      "45": -1,
      "46": -1,
      "49": -1,
      "50": -1,
      "57": -1,
      "58": -1,
      "59": -1,
      "60": -1,
      "61": -1,
      "63": -1,
      "64": -1,
      "65": -1,
      "66": -1,
      "69": -1,
      "72": -1,
      "73": -2,
      "85": -1,
      "86": -1,
      "88": -1,
      "90": -1,
      "97": -1,
      "98": -1,
      "99": -1,
      "100": -1,
      "102": -1,
      "103": -1,
      "105": -1,
      "106": -1,
      "107": -1,
      "110": -1,
      "112": -2,
      "125": -1,
      "127": -1,
      "128": -1,
      "131": -1,
      "132": -1,
      "133": -1,
      "134": -1,
      "135": -1,
      "136": -1,
      "139": -1,
      "140": -1,
      "141": -1,
      "144": -1,
      "145": -2,
      "156": -1,
      "157": -1,
      "159": -1,
      "162": -1,
      "164": -1,
      "165": -1,
      "168": -1,
      "169": -1,
      "170": -1,
      "172": -1,
      "173": -1,
      "178": -1,
      "180": -1,
      "181": -2,
      "192": -1,
      "193": -1,
      "196": -1,
      "198": -1,
      "199": -1,
      "200": -1,
      "202": -1,
      "203": -1,
      "204": -1,
      "210": -1,
      "212": -1,
      "213": -2,
      "224": -1,
      "225": -1,
      "228": -1,
      "229": -1,
      "232": -1,
      "233": -1,
      "235": -1,
      "238": -1,
      "239": -1,
      "242": -1,
      "243": -1,
      "246": -1,
      "247": -1,
      "250": -1,
      "251": -2,
      "258": -1,
      "259": -1,
      "260": -1,
      "262": -1,
      "263": -1,
      "267": -1,
      "274": -1,
      "275": -1,
      "276": -1,
      "278": -1,
      "288": 1,
      "290": 1,
      "291": 1,
      "293": 1,
      "294": 1,
      "297": -1,
      "298": -1,
      "301": -1,
      "303": -1,
      "310": 1,
      "311": 1,
      "313": 1,
      "314": -1,
      "317": 1,
      "318": 1,
      "320": 1,
      "321": 1,
      "322": -1,
      "324": 1,
      "325": -1,
      "327": -1,
      "328": -1,
      "331": -1,
      "332": -1,
      "335": -1,
      "337": -1,
      "338": -1,
      "341": -1,
      "342": -1,
      "343": -1,
      "345": -1,
      "347": 1,
      "348": -1,
      "350": -1,
      "351": -1,
      "354": -1,
      "356": -1,
      "357": -1,
      "360": -1,
      "362": 1,
      "363": 1,
      "364": 1,
      "366": -1,
      "367": -1,
      "370": -1,
      "372": -1,
      "374": -2,
      "381": 1,
      "382": 1,
      "384": 1,
      "385": 1,
      "387": 1,
      "389": 1,
      "390": 1,
      "391": 1,
      "394": 1,
      "395": 1
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Profile\/Factory.php": {
      "41": -1,
      "50": -1,
      "51": -2,
      "60": -1,
      "61": -2,
      "73": -1,
      "75": -1,
      "76": -1,
      "79": -1,
      "80": -1,
      "93": -1,
      "94": -1,
      "97": -1,
      "99": -1,
      "100": -2
    },
    "\/var\/www\/html\/vendor\/composer\/autoload_static.php": {
      "60": -1,
      "61": -1,
      "62": -1,
      "63": -1,
      "65": -1,
      "66": -2
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Command\/ListLength.php": {
      "26": -1,
      "27": -2
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Command\/ListPopFirstBlocking.php": {
      "26": -1,
      "27": -2,
      "34": -1,
      "35": -1,
      "36": -1,
      "39": -1,
      "40": -2
    },
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Configuration\/ProfileOption.php": {
      "34": -1,
      "40": -1,
      "42": -1,
      "49": -1,
      "50": -1,
      "51": -1,
      "52": -1,
      "53": -1,
      "56": -1,
      "57": -2,
      "64": -1,
      "65": -1,
      "67": -1,
      "68": -2
    },
    "\/var\/www\/html\/vendor\/composer\/autoload_real.php": {
      "11": -1,
      "12": -1,
      "14": -1,
      "21": -1,
      "22": -1,
      "25": -1,
      "27": -1,
      "28": -1,
      "29": -1,
      "31": -1,
      "32": -1,
      "34": -1,
      "36": -1,
      "37": -1,
      "38": -1,
      "39": -1,
      "41": -1,
      "43": 1,
      "44": 1,
      "45": -1,
      "48": 1,
      "49": -2
    }
  },
  "md5": {
    "\/var\/www\/html\/vendor\/soarce\/client\/src\/Pipe\/Handler.php": "bfc920ae414de67226e7d61a8b958812",
    "\/var\/www\/html\/vendor\/soarce\/client\/src\/RedisMutex.php": "9164829d48e8436ec02ec6f25d59ad1d",
    "\/var\/www\/html\/vendor\/soarce\/client\/src\/RequestTracking.php": "6e5f51f2851e061c8d8dc1aa1d29a520",
    "\/var\/www\/html\/vendor\/soarce\/client\/src\/execute.php": "c2f42993fe16ce12738797fb809cb4e5",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Command\/Command.php": "0254e4c89e344fba56b56487b1224fab",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Connection\/AbstractConnection.php": "1e675e40324b9a1305d5cac1c0ceed92",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Configuration\/Options.php": "6882ebc8110bfc940f5f7a14520c9571",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Command\/KeyExpire.php": "ee5118fa7bb5e0e314206a7f55f14316",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Command\/ListRemove.php": "e23c1178b5d83dbf220409910e24fa4d",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Connection\/Factory.php": "04d975d392fc55e8e94c24803c86f388",
    "\/var\/www\/html\/vendor\/soarce\/client\/src\/FrontController.php": "700cb7f9cb9091b9580ca030c005f776",
    "\/var\/www\/html\/vendor\/symfony\/deprecation-contracts\/function.php": "1a356b2db7f4f1552b1cc85206d22eca",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Connection\/Parameters.php": "42684e5ff14bd445d5d5ea44f2d10ccf",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Command\/ListPopLastBlocking.php": "197f153d8b65baf82380222b1594057f",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Profile\/RedisVersion320.php": "5ee9468a7b7c8c3e2d1e775f79de9805",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Profile\/RedisProfile.php": "d65fd5ae63ee0f9962345cfc8574960d",
    "\/var\/www\/html\/vendor\/composer\/ClassLoader.php": "c02be6d96671f88d28aad3ffa134c8ae",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Command\/ListPushTail.php": "7dafc5315b61c4429a34c36ae2879640",
    "\/var\/www\/html\/vendor\/autoload.php": "fdc0be12689a36faf3ab8e1ddef32b0e",
    "\/var\/www\/html\/details.php": "ebf160a5f2c791bac628aed610cc9f24",
    "\/var\/www\/html\/vendor\/soarce\/client\/src\/Config.php": "845289938eb4f68696f4abe73cc62677",
    "\/var\/www\/html\/index.php": "917aeddb72984650859ef9e192c32c30",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Client.php": "0c049c34078ae1010e225de29e590189",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Configuration\/ConnectionFactoryOption.php": "f1a8155b409454673aa5580909069cac",
    "\/var\/www\/html\/vendor\/soarce\/client\/src\/Pipe.php": "9010e00e6e45a106fe21f94917e09fe2",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Command\/ListPushHead.php": "8c141d4cec0ff04752caebc244b32711",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Connection\/StreamConnection.php": "d99a205dd7e2e85783340b9ef8a4aef6",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Profile\/Factory.php": "94955618b61c4c3ea2c4efaab93dab42",
    "\/var\/www\/html\/vendor\/composer\/autoload_static.php": "e92cd337e2447d1f0917b7957628cd4d",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Command\/ListLength.php": "3c7ea279ec1b0d0542f14784cb6bebfa",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Command\/ListPopFirstBlocking.php": "b3ac4ab20e69f789792c3bff7f066448",
    "\/var\/www\/html\/vendor\/predis\/predis\/src\/Configuration\/ProfileOption.php": "c6aa18fe0464db00b33ad2760abab1b8",
    "\/var\/www\/html\/vendor\/composer\/autoload_real.php": "8fafd8969d9b309aad4b7c2ff6a3857e"
  }
}


###

